
const data = {

  lunch: {
    name: [
      "mushrooms",
      "peas",
      "sazon",
      "tomatoes",
      "cookies",
      "artificial sweetener",
      "bean sprouts",
      "garlic powder",
      "cantaloupes",
      "chives",
      "croutons",
      "cream of tartar",
      "chestnuts",
      "grits",
      "sauerkraut",
      "parsnips",
      "lemon juice",
      "heavy cream",
      "chai",
      "ale",
      "baguette",
      "condensed milk",
      "flour",
      "brussels sprouts",
      "veal",
      "kumquats",
      "lettuce",
      "lentils",
      "cauliflower",
      "kidney beans",
      "turtle",
      "white beans",
      "salt",
      "bagels",
      "celery",
      "almonds",
      "catfish",
      "ricotta cheese",
      "pumpkin seeds",
      "chocolate",
      "brazil nuts",
      "pecans",
      "corn",
      "bay leaves",
      "jicama",
      "onions",
      "red beans",
      "Tabasco sauce",
      "Goji berry",
      "honeydew melons",
      "mozzarella",
      "red snapper",
      "blue cheese",
      "apples",
      "unsweetened chocolate",
      "pecans",
      "alfredo sauce",
      "guavas",
      "black-eyed peas",
      "tortillas",
      "margarine",
      "sushi",
      "bay leaves",
      "capers",
      "rice paper",
      "alligator",
      "pomegranates",
      "Havarti cheese",
      "poppy seeds",
      "cheddar cheese",
      "cactus",
      "pickles",
      "oatmeal",
      "olive oil",
      "tonic water",
      "molasses",
      "Worcestershire sauce",
      "shallots",
      "garlic",
      "mesclun greens",
      "curry powder",
      "trout",
      "curry leaves",
      "barley sugar",
      "adobo",
      "tuna",
      "bacon grease",
      "eggs",
      "bard",
      "fennel",
      "butter",
      "clams",
      "chile peppers",
      "red beans",
      "black beans",
      "leeks",
      "romaine lettuce",
      "pumpkins",
      "cocoa powder",
      "tomato paste"
    ],

    des: [
      "A light yoghurt",
      "A crunchy salad",
      "A crunchy salad",
      "Fresh redcurran",
      "A crunchy salad",
      "Fresh damson an",
      "Cornmeal and pe",
      "A crisp salad f",
      "Gochu jang and ",
      "Fresh beetroot ",
      "A crisp salad f",
      "A crisp salad f",
      "Bean and prosci",
      "A crunchy salad",
      "Lea bacon and f",
      "Pork sausage me",
      "A crunchy salad",
      "A crunchy salad",
      "Marinaded tofu ",
      "Tripe and cider",
      "Sharon fruit an",
      "A crunchy salad",
      "Kalonji and swe",
      "Black mustard s",
      "A crisp salad f",
      "A crunchy salad",
      "A crunchy salad",
      "Pecan and baby ",
      "A crisp salad f",
      "A crunchy salad",
      "A crisp salad f",
      "Limpa and fresh",
      "Fresh mangetout",
      "Fresh quinoa an",
      "Mizuna and rain",
      "Socca and tiger",
      "A crisp salad f",
      "A crisp salad f",
      "A crisp salad f",
      "A crunchy salad",
      "A crisp salad f",
      "A crunchy salad",
      "Dulse and kaffi",
      "A crisp salad f",
      "Bouquet garni a",
      "Radiatori and e",
      "A crisp salad f",
      "Free-range turk",
      "A crunchy salad",
      "A crunchy salad",
      "Spaghetti and e",
      "Instant coffee ",
      "A crisp salad f",
      "Fresh cloudberr",
      "A crunchy salad",
      "Fresh shallot a",
      "A crisp salad f",
      "Poussin and ita",
      "A crisp salad f",
      "Squid and pork ",
      "A crunchy salad",
      "Phyllo and fres",
      "A crisp salad f",
      "Cornstarch and ",
      "A crisp salad f",
      "Crab and fresh ",
      "Fresh elderberr",
      "A crunchy salad",
      "Savoy cabbage a",
      "A crisp salad f",
      "A crunchy salad",
      "Fresh arugula a",
      "Fresh blueberry",
      "Fresh rambutan ",
      "A crisp salad f",
      "A crisp salad f",
      "A crisp salad f",
      "A crisp salad f",
      "A crunchy salad",
      "Grappa and biso",
      "A crisp salad f",
      "A crunchy salad",
      "A crisp salad f",
      "Chinese cabbage",
      "Cham and roaste",
      "Romaine lettuce",
      "A crisp salad f",
      "Tubetti and mas",
      "Fresh kale and ",
      "A crisp salad f",
      "A crisp salad f",
      "A crisp salad f",
      "A crunchy salad",
      "A crisp salad f",
      "Denjang and mus",
      "A crisp salad f",
      "A crunchy salad",
      "Goat cheese and",
      "Chicory and she",
      "A crunchy salad",
    ]
  },

  dinner: {
    name: [
      "Caprese Zucchini Noodle Salad",
      "Chipotle Chicken Grilled Cheese",
      "Mediterranean Crab",
      "Chicken Fajita Casserole",
      "Bird's Nest Egg Salad",
      "Caprese Mac and Cheese",
      "Faggots with onion gravy",
      "Low Carb Peanut Butter",
      "Super Mom Stir Fry",
      "Penne Beef",
      "Flattened Chicken",
      "Pork Chops Romano",
      "Grilled chicken with chilli",
      "Coconut Pound Cake",
      "Steak Sandwiches",
      "Chicken and Corn Chowder",
      "Creamy Green Chile",
      "Healthy Chicken Burgers",
      "Grilled Pork Chops",
      "Shepherd's Pie",
      "Fruit Salad",
      "Slow-Cooker",
      "Spinach",
      "Pan-seared Salmon",
      "Snapper",
      "Chicken Fajita Burgers",
      "Chicken Cacciatore",
      "Guinea fowl tagine",
      "Skinnified Pork",
      "Salmon Sandwiches with Fries",
      "Stir-Fried Udon",
      "Instant Pot Turkey Chili",
      "The TJ Hooker Pizza",
      "Slow Cooker ",
      "Beef Curry",
      "Pork Tacos",
      "Roasted Summer",
      "Grilled Watermelon Salad",
      "Mexican Chicken",
      "Coconut",
      "Cheesy Chicken",
      "Sweet Thai Shrimp Curry",
      "Roasted Garlic Macaroni and Cheese ",
      "One Pot Garlic Butter Chicken",
      "Slow Cooker Chicken",
      "Grilled Chicken",
      "Kale Pesto Avocado",
      "Slow Cooker Meatball Subs",
      "Contest-Winning",
      "Chicken Salad",
      "Seared Scallops",
      "Skirt Steak",
      "Almond-Thyme-Crusted Mahi Mahi",
      "Seared Short Rib",
      "Creamy Baked Risotto",
      "Creamy chicken & mango curry",
      "Smoked Salmon",
      "Spinach Burrata",
      "Golden Beet",
      "Cornmeal-Crusted Catfish",
      "Minty carrot",
      "Bang-Bang Shrimp",
      "Pan-Seared Cod",
      "Slow Cooker Coq au Vin",
      "Calamari",
      "Homemade Creamy",
      "Avocado BLT",
      "Oven Baked Chicken Tacos",
      "Thai Peanut Chicken",
      "Tofu Kabobs",
      "Greek pasta salad",
      "Tacos",
      "Ravioli",
      "French Toast",
      "Coleslaw",
      "Porridge",
      "Fried Egg",
      "Bratkartoffeln",
      "Chicken Nuggets",
      "Mashed Potato",
      "Mashed Potato",
      "Wrap",
      "Lasagne",
      "Egg Fried Rice",
      "Spaghetti Bolognese",
      "Cucumber Salad",
      "Spaetzle",
      "Quesadilla",
      "Scallops",
      "Ravioli",
      "Tiramisu",
      "Couscous",
      "Antipasto",
      "French Toast",
      "Ratatouille",
      "Bratwurst",
      "Chicken Nuggets",
      "Barbecue",
      "Chicken Noodle Soup",
      "Apple Pie"
    ],

    des: [
      "Sit est adipisci aut",
      "Assumenda voluptatum",
      "Sequi natus velit.  ",
      "Et natus earum et si",
      "Velit libero sit nih",
      "Voluptatibus ducimus",
      "Corporis laudantium ",
      "Dolorum nemo dolores",
      "In amet eveniet iste",
      "Iste fugiat vero dol",
      "Soluta corporis dese",
      "Adipisci deleniti si",
      "Eos occaecati ut.   ",
      "Veritatis ut assumen",
      "Ut eligendi ut.     ",
      "Qui est nesciunt est",
      "Totam quidem autem v",
      "Officiis incidunt re",
      "Consequatur et error",
      "Aut aut fuga recusan",
      "Qui hic laudantium l",
      "Fugit recusandae cum",
      "Asperiores sunt veli",
      "Vitae voluptas eum a",
      "Esse recusandae aper",
      "Eos excepturi non ip",
      "Doloribus totam temp",
      "Sint dignissimos quo",
      "Blanditiis labore ve",
      "Quod dolor sed.     ",
      "Fuga quia aspernatur",
      "Blanditiis aliquam m",
      "Rerum et error totam",
      "Vero fugiat eum veni",
      "Voluptatem quam est ",
      "Cum sapiente labore ",
      "Harum dolorem recusa",
      "Omnis exercitationem",
      "Nihil aspernatur rei",
      "Consequatur doloribu",
      "In qui culpa ducimus",
      "Et molestiae officia",
      "Vero voluptatum nisi",
      "Nemo quisquam molest",
      "Sequi quia qui paria",
      "Recusandae quidem fa",
      "Labore libero reicie",
      "Non quisquam iusto u",
      "Distinctio et corrup",
      "Earum libero esse.  ",
      "Est sapiente iusto n",
      "Et ad voluptas id.  ",
      "Odit quisquam minima",
      "Similique non sunt a",
      "Nihil eius vero.    ",
      "Sed molestiae illo e",
      "Quaerat quae quidem ",
      "Dolorem at ex sapien",
      "Nulla itaque assumen",
      "Numquam et maiores. ",
      "Ducimus consequuntur",
      "Ipsam sit debitis au",
      "Ut qui tenetur verit",
      "Et quasi excepturi q",
      "Rem accusamus sed.  ",
      "Consequuntur sint hi",
      "Deleniti veniam illu",
      "Deserunt molestiae e",
      "Corrupti non et dolo",
      "Voluptatem consectet",
      "Id harum et.        ",
      "Incidunt sint quasi ",
      "Qui et nesciunt et d",
      "At laboriosam sunt. ",
      "Labore porro minima ",
      "Nihil repudiandae su",
      "Eveniet error pariat",
      "Voluptatem et volupt",
      "Officia voluptatibus",
      "Mollitia enim volupt",
      "Dolorem et odit veli",
      "Neque doloribus labo",
      "Quos qui pariatur vo",
      "Doloremque explicabo",
      "Voluptatibus repudia",
      "Ea sint eum odit nat",
      "Nostrum asperiores e",
      "Impedit consectetur ",
      "Labore facere impedi",
      "Recusandae sint hic ",
      "Iure neque aut repel",
      "Et voluptatem volupt",
      "Rerum suscipit hic a",
      "Architecto qui ipsum",
      "Voluptatem natus mag",
      "Nisi molestiae et im",
      "Facilis ut voluptas ",
      "Enim modi facere a a",
      "Iure eum error sint.",
      "Saepe quisquam aliqu"
    ]
  },  

  dessert: {
    name: [
      "Teacake",
      "Happy Cake",
      "Heavy cake",
      "Herman cake",
      "Hot milk cake",
      "Hummingbird cake ",
      "Kalathappam",
      "Kek Lapis Sarawak",
      "Kentucky jam cake",
      "Sheet cake",
      "Simnel cake",
      "Snack cake",
      "Sno Balls",
      "Song gao",
      "Spanische Windtorte",
      "Spekkoek",
      "Spice cake",
      "Sponge cake",
      "St. Honoré cake",
      "Stack cake",
      "Stollen",
      "Streuselkuchen",
      "Swiss roll",
      "Tahinopita",
      "Taiyaki",
      "Tarta de Santiago",
      "Tea loaf",
      "Teacake",
      "Tin roof pie",
      "Tipsy cake",
      "Tiramisu",
      "Brownie",
      "Buccellato",
      "Buckwheat gateau",
      "Bulla cake",
      "Bundt cake",
      "Butter cake",
      "Butterkuchen",
      "Pandan cake",
      "Panforte",
      "Panettone",
      "Panpepato",
      "Parkin",
      "Parrozzo",
      "Pastiera",
      "Petit four",
      "Eccles cake ",
      "Eggies",
      "Eierschecke ",
      "Erotic cake ",
      "Wacky cake  ",
      "Wafer",
      "Waffle",
      "Wedding cake",
      "Welsh cake",
      "White sugar sponge cake",
      "Wine cake",
      "Mampostial",
      "Manjar",
      "Maple sugar",
      "Maple taffy",
      "Marron glacé",
      "Marshmallow",
      "Marshmallow creme",
      "Marzipan",
      "Mendiant",
      "Milk chocolate ",
      "Mint",
      "Misri",
      "Modjeska",
      "Mooncake",
      "Moustalevria",
      "Mozartkugel",
      "Semifreddo",
      "Shave ice",
      "Shaved ice",
      "Slush",
      "Sno-ball",
      "Snow cone",
      "Snow cream",
      "Soft serve",
      "Sorbet",
      "Spoom",
      "Ice cream bar",
      "Ice cream cake",
      "Ice cream cone",
      "Ice cream float",
      "Ice cream sandwich ",
      "Ice cream soda",
      "Ice milk",
      "Indian ice cream (Alaska) ",
      "Indian ice cream (Canada) ",
      "Banitsa",
      "Banket",
      "Bear claw",
      "BeaverTails",
      "Belekoy",
      "Belokranjska povitica",
      "Bethmännchen",
      "Birnbrot"
    ],

    des: [
      "Quibusdam ut quia.   ",
      "Eos voluptas perferen",
      "Sit ipsum suscipit li",
      "Est asperiores nulla ",
      "Ullam sequi eaque qua",
      "Minima dolorum sed et",
      "Et doloremque laborum",
      "Enim quae ut et asper",
      "Et tempora quam autem",
      "Ad omnis aut ut labor",
      "Asperiores et eaque i",
      "Tempora ea necessitat",
      "Et repellat est.     ",
      "Voluptatem illo sunt ",
      "Hic sit voluptatem ve",
      "Labore ab aut est pra",
      "Nam hic voluptatem po",
      "Magni eum consequuntu",
      "Odio porro aliquam.  ",
      "Et perferendis culpa ",
      "Sint vero qui sunt es",
      "Tempore aliquam enim ",
      "Perferendis id et nec",
      "Nihil omnis dolores. ",
      "Veniam qui eaque est ",
      "Deserunt est quisquam",
      "Est autem enim nihil ",
      "Voluptas occaecati ut",
      "Rerum natus possimus ",
      "Quo quos impedit ut n",
      "Aut quas sed dolores ",
      "Iste veniam ut rerum.",
      "Itaque eum voluptas a",
      "Et nobis doloribus so",
      "Reprehenderit nulla e",
      "Amet sint molestiae c",
      "Iure suscipit repudia",
      "Corporis consequatur ",
      "Quis et deleniti inci",
      "Cumque optio suscipit",
      "Quam eius fuga magni ",
      "Sed similique et reru",
      "Aut dolor quia nulla ",
      "Eum eligendi et quia ",
      "Consequuntur praesent",
      "Neque natus ipsam ali",
      "Vel odio molestiae.  ",
      "Veritatis sunt optio ",
      "Sit voluptatum amet n",
      "Quo et et repellendus",
      "Quis sapiente impedit",
      "Saepe quibusdam debit",
      "Quod enim itaque hic.",
      "Magni iusto explicabo",
      "Ipsa iure voluptatem ",
      "Aut corrupti molestia",
      "Facilis ex qui sed du",
      "Provident id itaque s",
      "Voluptas est consequu",
      "Modi delectus natus v",
      "Consectetur sit praes",
      "Numquam voluptas et r",
      "Itaque corrupti commo",
      "Id est sit aperiam in",
      "Repellendus sit et sa",
      "Et quo reiciendis arc",
      "Quos mollitia eaque m",
      "Saepe quas et et labo",
      "Perspiciatis ut ea so",
      "Aliquid fuga id.     ",
      "Illo nulla officia an",
      "Animi ullam labore co",
      "Quod iusto omnis dolo",
      "Harum voluptatem temp",
      "Et ipsam nulla aliqui",
      "Distinctio voluptas a",
      "Labore voluptatem vol",
      "Repellendus inventore",
      "Et porro qui.        ",
      "Veritatis dolore labo",
      "Veniam repudiandae do",
      "Dicta dolor non neque",
      "Rerum suscipit volupt",
      "Quidem rerum maxime v",
      "Odio et quis quasi ul",
      "Possimus quo maiores ",
      "Quia laudantium volup",
      "Excepturi eos corpori",
      "Aut sed non quidem.  ",
      "Iusto error temporibu",
      "Reiciendis quia nisi ",
      "Esse commodi est dolo",
      "Architecto voluptate ",
      "Animi sapiente qui co",
      "Ut sequi in pariatur ",
      "Veritatis ut veritati",
      "Ipsam modi est eum li",
      "Veniam est nisi qui n",
      "Inventore labore blan",
      "Inventore deserunt er"
    ],
  }
};

module.exports = data;
